### ISSUE TITLE
it seems that that the fixed allocation for token is not working always 

### ISSUE THREAD

**Issue by ido777** [AutoLLM/ArxivDigest#19]
See https://github.com/AutoLLM/ArxivDigest/actions/runs/5211830320/jobs/9412353014#step:5:102 for example.

I also experienced a JSON parse error due to a response that was cut in the middle.

**Comment by rmfan** [comment]
This issue occurs when the prompts are too long for gpt-3.5-turbo. I'll add some code to back off with fewer abstracts in the block if the length limit is exceeded. The primary concern is that we don't currently have a way of normalizing relevance across calls to the language model, so we want as many abstracts grouped together as possible.

Here is the relevant code that will need to be changed: https://github.com/AutoLLM/ArxivDigest/blob/1912e8902615fbc45239ca33426f64eb85c02f7b/src/relevancy.py#L95

Do you have logs of the JSON parse error you encountered, to be sure that this is the same issue?

**Comment by ido777** [comment]
I didn't keep it, but I assume it is easy to reproduce. 
Some solutions I have seen is to calculate the ratio of the input token vs output tokens. To count input tokens and to limit the input 

Anyway I got an email from openai that they increased the limit AFAIR it cost more to use longer inference.

**Comment by rivercold** [comment]
Yes, you can replace the "gpt-3.5-turbo" to "gpt-3.5-turbo-16k" in https://github.com/AutoLLM/ArxivDigest/blob/main/src/relevancy.py#L143.  That extends the context lengths to 16k from 4k, and doubles the price.
